### ISSUE TITLE
css中，:after中`content: "...\a..\a." `的`\a`可以起到换行的作用

### ISSUE THREAD

**Issue by novlan1** [novlan1/technical-blog#2]
css中 `:after`中 `content: "...\a..\a." `的`\a`可以起到换行的作用

实现加载中...效果的一个方法是：

```css
animation: loading 3s infinite step-start both;

@keyframes loading {
 33% {
  transform: translate3d(0, -2em, 0);
 }
 66% {
  transform: translate3d(0, -1em, 0);
 }
}
```
