### ISSUE TITLE
CSS3 [attribute*=value] 选择器

### ISSUE THREAD

**Issue by novlan1** [novlan1/technical-blog#43]
实例：

设置 class 属性值包含 "test" 的所有 div 元素的背景色：

```css
div[class*="test"] {
  background:#ffff00;
}
```
