### ISSUE TITLE
div中img有间隙的解决方法：line-height: 0

### ISSUE THREAD

**Issue by novlan1** [novlan1/technical-blog#56]
div中img有间隙的解决方案就是用到了这个小小的属性   那么请看方案

方案1 给img 设置为display：block
```css
img{display:block}
```
第二种办法就是给外层的div添加line-height 设置为0 （none）也一样
```
div{line-height:0;}
```
