### ISSUE TITLE
scss中循环的使用

### ISSUE THREAD

**Issue by novlan1** [novlan1/technical-blog#60]
1、`@each in` 循环

使用一个变量： #{$变量名}
```scss
$colors: (
    p1: rgb(255, 113, 61),
    p2: lightblue,
    p3: lightseagreen
);
@each $key, $color in $colors {
    &.#{$key} {
         background-color: $color;
    }
}
```
2、`@for… from… to` 循环

```scss
@for $i from 1 to 4 {
    .paper:nth-child(#{$i}) {
        /**
        有顺序之分
        transform: translate() rotate() !== transform: rotate() translate()
        */
         transform: translate(-50%, -40%) rotate(#{$i}5deg);
     }
}
分别旋转15 25 35 45度
```

参考：[scss中循环的妙用](https://blog.csdn.net/swallowblank/article/details/108468926)
